# Generated by Django 5.2 on 2025-04-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'institute',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=50)),
                ('location_country', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('has_multimedia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'post',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'social_media',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manager_first_name', models.CharField(max_length=50)),
                ('manager_last_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institute_id', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.institute')),
            ],
            options={
                'db_table': 'project',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project_field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50, null=True)),
                ('project_id', models.ForeignKey(db_column='preject_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.project')),
            ],
            options={
                'db_table': 'project_field',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project_post',
            fields=[
                ('project_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.post')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.project')),
            ],
            options={
                'db_table': 'project_poost',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Analysis_result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('field_id', models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.project_field')),
                ('project_post_id', models.ForeignKey(db_column='project_post_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.project_post')),
            ],
            options={
                'db_table': 'analysis_result',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.social_media'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country_of_birth', models.CharField(max_length=50)),
                ('country_of_residence', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('media_id', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.social_media')),
            ],
            options={
                'db_table': 'user',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('repost_id', models.AutoField(primary_key=True, serialize=False)),
                ('repost_time', models.DateTimeField()),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.user')),
            ],
            options={
                'db_table': 'repost',
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='media_analysis.user'),
        ),
    ]
