# Generated by Django 4.2.18 on 2025-04-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                ("institute_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "institute",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("post_time", models.DateTimeField()),
                (
                    "location_city",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "location_state",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "location_country",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                ("has_multimedia", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "post",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("manager_first_name", models.CharField(max_length=50)),
                ("manager_last_name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "institute_id",
                    models.ForeignKey(
                        db_column="institute_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.institute",
                    ),
                ),
            ],
            options={
                "db_table": "project",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Social_media",
            fields=[
                ("media_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "social_media",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=40)),
                (
                    "first_name",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                ("last_name", models.CharField(default=None, max_length=50, null=True)),
                (
                    "country_of_birth",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "country_of_residence",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                ("age", models.IntegerField(default=None, null=True)),
                ("gender", models.CharField(default=None, max_length=20, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "media_id",
                    models.ForeignKey(
                        db_column="media_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.social_media",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Repost",
            fields=[
                ("repost_id", models.AutoField(primary_key=True, serialize=False)),
                ("repost_time", models.DateTimeField()),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.post",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.user",
                    ),
                ),
            ],
            options={
                "db_table": "repost",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Project_post",
            fields=[
                (
                    "project_post_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.post",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        db_column="project_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_post",
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Project_field",
            fields=[
                ("field_id", models.AutoField(primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=50)),
                (
                    "project_id",
                    models.ForeignKey(
                        db_column="project_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_field",
                "permissions": (),
            },
        ),
        migrations.AddField(
            model_name="post",
            name="media_id",
            field=models.ForeignKey(
                db_column="media_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="media_analysis.social_media",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="media_analysis.user",
            ),
        ),
        migrations.CreateModel(
            name="Analysis_result",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(default=None, max_length=255, null=True)),
                (
                    "field_id",
                    models.ForeignKey(
                        db_column="field_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.project_field",
                    ),
                ),
                (
                    "project_post_id",
                    models.ForeignKey(
                        db_column="project_post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media_analysis.project_post",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_result",
                "permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("media_id", "username"), name="unique_username_within_media"
            ),
        ),
        migrations.AddConstraint(
            model_name="project_post",
            constraint=models.UniqueConstraint(
                fields=("project_id", "post_id"), name="over_analysis"
            ),
        ),
        migrations.AddConstraint(
            model_name="project_field",
            constraint=models.UniqueConstraint(
                fields=("project_id", "field_name"),
                name="field_name_unique_within_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(("start_date__lte", models.F("end_date"))),
                name="start_date_before_or_equal_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                fields=("user_id", "media_id", "post_time"),
                name="one_post_one_time_a_user_within_a_media",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysis_result",
            constraint=models.UniqueConstraint(
                fields=("project_post_id", "field_id"),
                name="one_result_for_one_post_with_a_field_within_a_project",
            ),
        ),
    ]
