# Generated by Django 5.2 on 2025-04-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0002_alter_post_location_city_alter_post_location_country_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project_post',
            table='project_post',
        ),
    ]
