# Generated by Django 5.2 on 2025-04-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0003_alter_project_post_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_field',
            old_name='project_id',
            new_name='projject_id',
        ),
    ]
