# Generated by Django 5.2 on 2025-04-21 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0004_rename_project_id_project_field_projject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_field',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='media_analysis.project'),
            preserve_default=False,
        ),
    ]
